### ISSUE TITLE
not working clearMessageHistory();   clearMessages();

### ISSUE THREAD

**Issue by dominion56** [5exyGuy/altv-vchat#1]
i have some issues. I've try to clear messages after playr disconnect from server and nothing happened. Messages still there. 
here is the code `alt.on('playerDisconnect', playerDisconnect);

function playerDisconnect(player) {
  if (!player || !player.valid) {
    return;
  }
  let pos;
  let ID = player.getSyncedMeta('ID');
  pos = player.pos;

  global.DB.query(
    'UPDATE characters SET x=?, y=?, z=?, h=?, hp=?, armour=? WHERE uuid=?',
    [pos.x, pos.y, pos.z, pos.z - 1, player.health, player.armour, ID],
    function (err, r) {}
  );
  chat.clearMessageHistory(player);
  chat.clearMessages(player);
  alt.log(`${player.name} has disconnected from the server.`);
}`

maybe i do something wrong? can you help me?

**Comment by 5exyGuy** [comment]
Why would you want to clear messages on disconnect? It doesn't make any sense to do that, because the game gets shut down.
I'll need a better explanation what are you trying to achieve.

**Comment by dominion56** [comment]
i want to clear all messages when player disconnect because when player is connect again all old messages appears in chat. but now i think i can clear old messages after connect player not on disconnect

**Comment by 5exyGuy** [comment]
Also you can set `maxMessageHistory` to `0` in `options.json` if you're using the latest version.
