### ISSUE TITLE
Server crashed after use commands

### ISSUE THREAD

**Issue by woozievert** [5exyGuy/altv-vchat#2]
My gamemode - Clientside: JS, Serverside: C#
I got regiserCmd work, and command works well.
But after using the command, there is a crash without logs(errors), I can only judge that it is the crash after using the command.(Not typing!!!)
but sometimes it works, Doesn't seem to be a problem with registerCmd. I tested it without registerCmd, it crash my server too.
I put log test(server -> chat.ts):
`if (words.length > 0) {
                if (this.optionsService.getOption('logPlayerCommands'))
                    this.loggerService.log(`[Commmand] ${player.name}: ${message}`);

                let args = words.split(' ');
                let cmdName = args.shift() ?? '';

                const invoked = this.commandService.invoke(player, cmdName, args);

                logError("Invoked doing, result = " + invoked)

                if (invoked)
                {
                    logError("Invoked success, result = " + invoked)
                    return;
                }

                logError("Invoked failed, result = " + invoked)

                const unknownCommandMessage = this.optionsService
                    .getOption('unknownCommandMessage')
                    .replace('{0}', cmdName);

                try {
                    this.mountService.waitForMount(
                        player,
                        this.windowService.send(player, unknownCommandMessage, MessageType.Error),
                    );

                    logError("The command doesnt exists")
                }
                catch (e) {
                    logError(`[Error] ${e}`);
                }
            }`

i have no idea...

**Comment by alphasylvain** [comment]
maybe...
alt.emitClientRaw isn't compatible with C# server

Just replace alt.emitClientRaw() by alt.emitClient()
thx xenicle ^^
